### ISSUE TITLE
Small flaw on precision

### ISSUE THREAD

**Issue by manuel-reil** [louischatriot/exec-time#3]
Hi,

thanks for the module. I detected a small flaw in function Profiler.
In line 49 it should read:
`if (this.precision === 'ms') this.divisor = 1e6;`
instead of:
`if (precision === 'ms') this.divisor = 1e6;`

This prohibited the proper formatting in function formatTime.

Cheers,
Manuel

**Comment by louischatriot** [comment]
Indeed, thanks for pointing out. I fixed it.
